package report

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const otelGeneratedHeader = `# Fragment generated by coralogix-metrics-usage — paste under processors: in your OpenTelemetry Collector config (otelcol-contrib with filter + transform).
#
# Semantics:
#   metrics_usage_drop_unused_metrics — drops metrics that had zero referenced usage (no dashboard/alert/SLO matched any series).
#   metrics_usage_strip_unused_only_labels — for metrics that are still referenced, deletes datapoint attribute keys that appear on at least one unused series but never on any used series for that metric name.
#
# If the scan used --skip-dashboards, --skip-alerts, or --skip-slo, “usage” here reflects only the sources that were scanned (see metric_usage_summary.json warnings).
# Coralogix-internal metric names (prefix "cx_") are excluded from the catalog and from this output (see meta.coralogix_internal_metric_names_skipped).
#
# Prometheus scrape labels become datapoint attributes on the prometheusreceiver path; adjust statements if your pipeline differs.
#
# Suggested metrics pipeline order: [..., metrics_usage_drop_unused_metrics, metrics_usage_strip_unused_only_labels, ...]
#
# Stripping labels changes metric identity; validate in staging before production.

`

type metricLabelAgg struct {
	usedCount   int
	unusedCount int
	usedKeys    map[string]struct{}
	unusedKeys  map[string]struct{}
}

// OTELProcessorPlan mirrors the OTEL yaml fragment: one drop metric per filter entry,
// one strip statement per delete_key line (metric × label key).
type OTELProcessorPlan struct {
	DropMetricNames []string
	StripStatements []OTELStripStatement // one entry per YAML transform line
}

// OTELStripStatement matches a single delete_key(attributes,"label_key") where metric.name == metric_name OTTL line.
type OTELStripStatement struct {
	MetricName string
	LabelKey   string
}

// BuildOTELProcessorPlan derives drop/strip actions from used vs unused catalog series (same rules as the YAML writer).
func BuildOTELProcessorPlan(used []UsedSeries, unused []UnusedSeries) OTELProcessorPlan {
	agg := aggregateMetricLabels(used, unused)

	var drops []string
	type stripRule struct {
		metric string
		keys   []string
	}
	var strips []stripRule

	for mn, a := range agg {
		if a.unusedCount == 0 {
			continue
		}
		if a.usedCount == 0 {
			drops = append(drops, mn)
			continue
		}
		var keys []string
		for k := range a.unusedKeys {
			if k == "__name__" {
				continue
			}
			if _, ok := a.usedKeys[k]; !ok {
				keys = append(keys, k)
			}
		}
		sort.Strings(keys)
		if len(keys) > 0 {
			strips = append(strips, stripRule{metric: mn, keys: keys})
		}
	}

	sort.Strings(drops)
	sort.Slice(strips, func(i, j int) bool {
		if strips[i].metric != strips[j].metric {
			return strips[i].metric < strips[j].metric
		}
		return strings.Join(strips[i].keys, ",") < strings.Join(strips[j].keys, ",")
	})

	var stmts []OTELStripStatement
	for _, rule := range strips {
		for _, k := range rule.keys {
			stmts = append(stmts, OTELStripStatement{MetricName: rule.metric, LabelKey: k})
		}
	}

	return OTELProcessorPlan{DropMetricNames: drops, StripStatements: stmts}
}

func aggregateMetricLabels(used []UsedSeries, unused []UnusedSeries) map[string]*metricLabelAgg {
	out := make(map[string]*metricLabelAgg)
	get := func(mn string) *metricLabelAgg {
		a := out[mn]
		if a == nil {
			a = &metricLabelAgg{
				usedKeys:   make(map[string]struct{}),
				unusedKeys: make(map[string]struct{}),
			}
			out[mn] = a
		}
		return a
	}
	for _, s := range used {
		mn := s.Labels["__name__"]
		if mn == "" {
			continue
		}
		a := get(mn)
		a.usedCount++
		for k := range s.Labels {
			a.usedKeys[k] = struct{}{}
		}
	}
	for _, s := range unused {
		mn := s.Labels["__name__"]
		if mn == "" {
			continue
		}
		a := get(mn)
		a.unusedCount++
		for k := range s.Labels {
			a.unusedKeys[k] = struct{}{}
		}
	}
	return out
}

// OTELUnusedProcessorsYAML returns an otelcol-contrib processors fragment: filter (drop wholly-unused metrics)
// and transform (strip label keys that appear only on unused series for partially-used metrics).
func OTELUnusedProcessorsYAML(used []UsedSeries, unused []UnusedSeries) []byte {
	plan := BuildOTELProcessorPlan(used, unused)

	var b strings.Builder
	b.WriteString(otelGeneratedHeader)
	if len(plan.DropMetricNames) == 0 && len(plan.StripStatements) == 0 {
		b.WriteString("processors: {}\n")
		return []byte(b.String())
	}

	b.WriteString("processors:\n")

	if len(plan.DropMetricNames) > 0 {
		b.WriteString("  metrics_usage_drop_unused_metrics:\n")
		b.WriteString("    error_mode: ignore\n")
		b.WriteString("    metrics:\n")
		b.WriteString("      exclude:\n")
		b.WriteString("        match_type: strict\n")
		b.WriteString("        metric_names:\n")
		for _, mn := range plan.DropMetricNames {
			b.WriteString("          - ")
			b.WriteString(yamlQuotedScalar(mn))
			b.WriteByte('\n')
		}
	}

	if len(plan.StripStatements) > 0 {
		if len(plan.DropMetricNames) > 0 {
			b.WriteByte('\n')
		}
		b.WriteString("  metrics_usage_strip_unused_only_labels:\n")
		b.WriteString("    error_mode: ignore\n")
		b.WriteString("    metric_statements:\n")
		b.WriteString("      - context: datapoint\n")
		b.WriteString("        statements:\n")
		for _, stmt := range plan.StripStatements {
			b.WriteString("          - ")
			b.WriteString(ottlDeleteAttrStmt(stmt.LabelKey, stmt.MetricName))
			b.WriteByte('\n')
		}
	}

	return []byte(b.String())
}

func ottlDeleteAttrStmt(labelKey, metricName string) string {
	return fmt.Sprintf(`delete_key(attributes, %s) where metric.name == %s`,
		ottlStringLit(labelKey), ottlStringLit(metricName))
}

// ottlStringLit returns an OTTL double-quoted string literal body including quotes.
func ottlStringLit(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\', '"':
			sb.WriteByte('\\')
			sb.WriteRune(r)
		case '\n':
			sb.WriteString(`\n`)
		case '\r':
			sb.WriteString(`\r`)
		case '\t':
			sb.WriteString(`\t`)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// yamlQuotedScalar returns a YAML double-quoted scalar safe for metric names.
func yamlQuotedScalar(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\', '"':
			sb.WriteByte('\\')
			sb.WriteRune(r)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// WriteOTELUnusedProcessorsYAML writes OTELUnusedProcessorsYAML to path (0664).
func WriteOTELUnusedProcessorsYAML(path string, used []UsedSeries, unused []UnusedSeries) error {
	return os.WriteFile(path, OTELUnusedProcessorsYAML(used, unused), 0o644)
}
